### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by akashmittal18** [togethercomputer/OpenChatKit#87] opened 2023-04-04 09:16 UTC
While trying to implement **Pythia-Chat-Base-7B**  I am getting this error on running the very fist command (`python inference/bot.py --model togethercomputer/Pythia-Chat-Base-7B`) after creating and activating the conda env. 
Can anyone help to identify what could possibly be the issue?

**Comment by koonseng** [comment] 2023-04-07 09:24
I have the same problem. I'm running this on AWS g3.4xlarge model with 128GB of memory.

python3 inference/bot.py --model togethercomputer/Pythia-Chat-Base-7B
Loading togethercomputer/Pythia-Chat-Base-7B to cuda:0...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████| 2/2 [00:09<00:00,  4.55s/it]
Traceback (most recent call last):
  File "inference/bot.py", line 285, in <module>
    main()
  File "inference/bot.py", line 280, in main
    not args.no_stream,
  File "/usr/lib64/python3.7/cmd.py", line 105, in cmdloop
    self.preloop()
  File "inference/bot.py", line 127, in preloop
    self._model = ChatModel(self._model_name_or_path, self._gpu_id, self._max_memory)
  File "inference/bot.py", line 59, in __init__
    self._model.to(device)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/transformers/modeling_utils.py", line 1811, in to
    return super().to(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/ec2-user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

**Comment by koonseng** [comment] 2023-04-07 12:18
OK, solved it. The problem was the g3.4xlarge instance has only 8GB per GPU, clearly not enough. I re-ran this on a g5.2xlarge and the problem disappears.

**Comment by zas97** [comment] 2023-04-13 10:13
I have the same problem

**Comment by orangetin** [comment] 2023-04-13 15:42
@zas97 @akashmittal18  Could you please describe your setup? I see that a lot of people have this issue but I'm not able to reproduce it.

**Comment by zas97** [comment] 2023-04-14 15:00
I used paperspace gradient with a P500

**Comment by QDxiaoye** [comment] 2023-04-20 00:30
I had the same problem

**Comment by orangetin** [comment] 2023-04-21 20:46
This error is caused by Accelerate auto-offloading weights to either the cpu or disk because of insufficient memory on the GPU.

@zas97 can you try manually offloading weights using the `-g` and `-r` flags as suggested in these [docs](https://github.com/togethercomputer/OpenChatKit/tree/main/inference#arguments)? 

So on the g3.4xlarge (8GB VRAM, 122 GB memory) you'd run: 
`python inference/bot.py --model togethercomputer/Pythia-Chat-Base-7B -g 0:6 -r 120`. 
This will load up to 6 GB of the model onto the gpu and the rest into memory. 

This can work better with 8bit and #84 

@koonseng can you try this too?

**Comment by wemoveon2** [comment] 2023-05-06 21:19
> This error is caused by Accelerate auto-offloading weights to either the cpu or disk because of insufficient memory on the GPU.
> 
> @zas97 can you try manually offloading weights using the `-g` and `-r` flags as suggested in these [docs](https://github.com/togethercomputer/OpenChatKit/tree/main/inference#arguments)? You should be able to run it on a P5000 in 8bit.
> 
> So on the g3.4xlarge (8GB VRAM, 122 GB memory) you'd run: `python inference/bot.py --model togethercomputer/Pythia-Chat-Base-7B -g 0:6 -r 120`. This will load up to 6 GB of the model onto the gpu and the rest into memory.
> 
> This can work better with #84 as you'd be able to change the 6 to an 8.
> 
> @koonseng can you try this too?

@orangetin can you give more details regarding the exact cause of this error?

**Comment by orangetin** [comment] 2023-05-06 22:27
> @orangetin can you give more details regarding the exact cause of this error?

Sure! 

When loading the model using `device_map="auto"` on a GPU with insufficient VRAM, Transformers tries to offload the rest of the model onto the CPU/disk. The problem is, the model is being loaded in `float16` which is not supported by CPU/disk (neither is 8-bit). So, torch offloads the model as a meta-tensor (no data). In other words, parts of the model are missing.

Solutions:
- Using the `-g` and `-r` arguments: gives Accelerate a manual config for where it should offload the model. Accelerate takes care of the dtype.
- Loading the model using either float32 or bfloat16 should work. Note, I haven't tested this one out myself but it *should* work.
- Using a larger GPU like @koonseng did. This prevents offloading in the first place.

**Comment by wemoveon2** [comment] 2023-05-07 20:34
@orangetin Not sure if `float32` will solve this particular issue since that's been the cause of my issue (unrelated to this project, more specific to just the `accelerate` package). I've been trying to load model pipelines in `float32` with disk offload and have been getting this error inside `accelerate`'s helper function`modeling.py::set_module_tensor_to_device()` at `module._parameters[tensor_name] = new_value`.

There is [another thread documenting this same issue](https://github.com/tloen/alpaca-lora/issues/368) (occurs at the line, with a different torch version IIRC) in which the solution was resolved by using `float16`, but I think this only worked as there was no longer offloading going on.

@akashmittal18 did the proposed solution help resolve your issue? And if so, can you confirm whether you are still using CPU/disk offload along with the dtype assigned by `accelerate`?

**Comment by anujsahani01** [comment] 2023-06-02 14:21
> > @orangetin can you give more details regarding the exact cause of this error?
> 
> Sure @wemoveon2 !
> 
> When loading the model using `device_map="auto"` on a GPU with insufficient VRAM, Transformers tries to offload the rest of the model onto the CPU/disk. The problem is, the model is being loaded in `float16` which is not supported by CPU/disk (neither is 8-bit). So, torch offloads the model as a meta-tensor (no data). In other words, parts of the model are missing.
> 
> Solutions:
> 
> * Using the `-g` and `-r` arguments: gives Accelerate a manual config for where it should offload the model. Accelerate takes care of the dtype.
> * Loading the model using either float32 or bfloat16 should work. Note, I haven't tested this one out myself but it _should_ work.
> * Using a larger GPU like @koonseng did. This prevents offloading in the first place.


I am having the same problem i loaded the model checkpoint shards in both  float32 and bfloat16 but it does not work for me i do not know for what reason.

This is my google colab file its a request to have a look in it.
https://drive.google.com/file/d/1-ccrx1Q5tkLUYtZBGi5lNZGjPMyr_X9U/view?usp=sharing

AN OVERVIEW OF MY CODE:
i am using https://huggingface.co/HuggingFaceH4/starchat-alpha model, finetuning it on my own dataset. Firstly i using the meta device i made a device_map to load the checkpoint shards to my device , then i initialized my model using the downloaded checkpoints on my session storage then i loaded the weights tied them and finally i used acceletator load_checkpoint_and_dispatch and passed the folder contaning checkpoints  and .josn files which is giving me this error.

This is the code snip that is giving me error:
![image](https://github.com/togethercomputer/OpenChatKit/assets/83875986/fb694cc3-38b0-4030-ae3a-542632afb34a)

The error:
![image](https://github.com/togethercomputer/OpenChatKit/assets/83875986/45394678-5a2e-4a6c-8a8a-745434b68cfe)

my checkpoint folder that i am passing.
![image](https://github.com/togethercomputer/OpenChatKit/assets/83875986/13ffb322-5aed-4f32-b43f-40ac973582f7)

Please correct if i am conceptually wrong or missing some imp step.
I am using colab pro for running this code.

Thank You!
please help me in solving this error. @orangetin 
Your inputs will be highly appreciated.

**Comment by orangetin** [comment] 2023-06-02 17:12
@anujsahani01 I can't import your Colab file.

The error is caused by offloading model weights incorrectly. Refer to my previous comments on how to fix it:
- https://github.com/togethercomputer/OpenChatKit/issues/87#issuecomment-1518319626
- https://github.com/togethercomputer/OpenChatKit/issues/87#issuecomment-1537234491

Closing this thread as it is solved. Feel free to continue the conversation if you're still having issues.

**Closed by orangetin** 2023-06-02 17:12 UTC

**Comment by anujsahani01** [comment] 2023-06-02 19:09
> @anujsahani01 I can't import your Colab file.
> 
> The error is caused by offloading model weights incorrectly. Refer to my previous comments on how to fix it:
> 
> * [NotImplementedError: Cannot copy out of meta tensor; no data! #87 (comment)](https://github.com/togethercomputer/OpenChatKit/issues/87#issuecomment-1518319626)
> * [NotImplementedError: Cannot copy out of meta tensor; no data! #87 (comment)](https://github.com/togethercomputer/OpenChatKit/issues/87#issuecomment-1537234491)
> 
> Closing this thread as it is solved. Feel free to continue the conversation if you're still having issues.

Thank You ! 
Can you please tell how to run these commands on my google colab?

**Comment by zetyquickly** [comment] 2023-08-29 23:51
> > @orangetin can you give more details regarding the exact cause of this error?
> 
> Sure @wemoveon2 !
> 
> When loading the model using `device_map="auto"` on a GPU with insufficient VRAM, Transformers tries to offload the rest of the model onto the CPU/disk. The problem is, the model is being loaded in `float16` which is not supported by CPU/disk (neither is 8-bit). So, torch offloads the model as a meta-tensor (no data). In other words, parts of the model are missing.
> 
> Solutions:
> 
> * Using the `-g` and `-r` arguments: gives Accelerate a manual config for where it should offload the model. Accelerate takes care of the dtype.
> * Loading the model using either float32 or bfloat16 should work. Note, I haven't tested this one out myself but it _should_ work.
> * Using a larger GPU like @koonseng did. This prevents offloading in the first place.

Based on what was said, reordering the commands might provide a solution:
```
# first do
pipe = pipe.to(device)
# then do
pipe.enable_sequential_cpu_offload()
```
Ofc if the model itself (without inference data) can fit into VRAM
