### ISSUE TITLE
ResolvePackageNotFound:   - nccl=2.12.12.1

### ISSUE THREAD

**Issue by ArchaeopteryxGu** [togethercomputer/OpenChatKit#48] opened 2023-03-16 09:57 UTC
When I try to creat the environment,it happens.
I run it on the Windows.

**Comment by orangetin** [comment] 2023-03-18 00:59
Duplicate of #19 . nccl only supports Linux. Can be fixed by using WSL.

**Comment by csris** [comment] 2023-03-18 05:04
Yep, this appears to be a dupe of #19. @ArchaeopteryxGu, can you try with WSL?

**Closed by csris** 2023-03-18 05:04 UTC
