### ISSUE TITLE
Environment Issues On Mac

### ISSUE THREAD

**Issue by arokhsaz3** [togethercomputer/OpenChatKit#137] opened 2023-06-11 18:54 UTC
Hello,
I run $ mamba env create -f environment.yml $, and I receive a package compatibility error that I have shown in the screenshot below. What can I do to fix this issue? Up until then everything seems to run correctly.
Thanks!

I am trying to install under these conditions:
-  macOS 13.1 (22C65).
- Python 3.9.16
- conda 23.3.1

<img width="1134" alt="Screenshot 2023-06-11 at 2 53 52 PM" src="https://github.com/togethercomputer/OpenChatKit/assets/59941999/91e0930a-7806-4e6a-b87b-377eeb65c660">

**Comment by orangetin** [comment] 2023-06-11 19:22
Macs are not supported by OCK. A lot of the packages that you're seeing fail require a CUDA GPU (which Macs don't have).

There's a workaround, but do note that inference will be slow (because CPU/MPS), and training is not supported: [see this comment](https://github.com/togethercomputer/OpenChatKit/issues/45#issuecomment-1560404201)

I'd recommend [redpajama.cpp](https://github.com/togethercomputer/redpajama.cpp) for inference or running OCK on a GPU device.

Dupe of #45

**Closed by orangetin** 2023-06-11 19:22 UTC
